version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./data:/Taxi_App/data

  backend_test:
    build: ./backend
    volumes:
      - ./data:/Taxi_App/data
    command: pytest tests/ -v

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend