version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=taxiapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./data:/Taxi_App/data
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - db
    env_file:
      - .env

  backend_test:
    build: ./backend
    volumes:
      - ./data:/Taxi_App/data
    environment:
      - DATABASE_URL=${DATABASE_TEST_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    command: pytest tests/ -v
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_API_URL=http://backend:5000/api
    depends_on:
      - backend
    env_file:
      - .env

volumes:
  postgres_data: